openapi: 3.0.0
info:
  title: Flickr Search By Tag API
  description: Flickr Search By Tag API
  version: '3.01'
servers:
  - url: http://localhost:8000/
paths:
  /search:
    get:
      description: Search Flickr photos.
      parameters:
        - $ref: '#/components/parameters/text'
        - $ref: '#/components/parameters/tags'
        - $ref: '#/components/parameters/tag_mode'
        - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    text:
      name: text
      in: query
      required: false
      schema:
        type: string
      example: animals
    tags:
      name: tags
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      example: [cat, dog]
    tag_mode:
      name: tag_mode
      in: query
      required: false
      schema:
        type: string
        enum: [any, all]
      example: all
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      example: 10
  schemas:
    SearchResponse:
      type: object
      properties:
        photos:
          type: object
          properties:
            page:
              type: integer
            pages:
              type: integer
            perpage:
              type: integer
            total:
              type: integer
            photo:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  url:
                    type: string
        stat:
          type: string
security:
  - bearerAuth: []
